# Generated by Django 5.2.3 on 2025-06-23 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='品項名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='每日租金')),
                ('image_url', models.URLField(blank=True, help_text='請提供品項圖片的URL', null=True, verbose_name='圖片URL')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('category', models.CharField(choices=[('camera', '相機'), ('lens', '鏡頭'), ('other', '其他品項')], default='camera', max_length=20, verbose_name='品項類別')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='推薦商品 (顯示於首頁)')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='請輸入您的姓名', max_length=100, verbose_name='租賃者姓名')),
                ('email', models.EmailField(help_text='請輸入您的電子郵件地址', max_length=254, verbose_name='電子郵件')),
                ('start_date', models.DateField(verbose_name='租賃開始日期')),
                ('end_date', models.DateField(verbose_name='租賃結束日期')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='總租金')),
                ('status', models.CharField(choices=[('pending', '待確認'), ('active', '租賃中'), ('returned', '已歸還'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='租賃狀態')),
                ('rented_at', models.DateTimeField(auto_now_add=True, verbose_name='預訂時間')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.item', verbose_name='租賃商品')),
            ],
            options={
                'verbose_name': '租賃訂單',
                'verbose_name_plural': '租賃訂單',
                'ordering': ['-rented_at'],
            },
        ),
    ]
